version: '3'
services:
  web-1:
    environment:
      - HAB_LICENSE
    image: $HAB_ORIGIN/webapp
  web-2:
    environment:
      - HAB_LICENSE
    image: $HAB_ORIGIN/webapp
    command: --peer web-1
    depends_on:
      - web-1
  load-balancer:
    environment:
      - HAB_LICENSE
    image: $HAB_ORIGIN/haproxy
    command: --peer web-2
             --bind backend:webapp.default
    ports:
      - 8000:80
    depends_on:
      - web-2
